### ISSUE TITLE
大神，可以帮解决一下么

### ISSUE THREAD

**Issue by TongJiaqi0123** [nodfe/go_moso#4]
Traceback (most recent call last):
  File "E:\桌面\go_moso-master\moso.py", line 133, in <module>
    answerRows = getSubJectAnswer(opener,userId)
  File "E:\桌面\go_moso-master\moso.py", line 48, in getSubJectAnswer
    trueRate = item.find(attrs={"style": "color:#07AC6C;"}).string
AttributeError: 'NoneType' object has no attribute 'string'

**Comment by nodfe** [comment]
看起来像应该是没获取到问题或者是蓝墨云更新过了，现在脚本已经不更新了，抱歉
